# Site settings
title: Vasilis Angelidis
description: My bio | 1st assessment of the Mobile and Pervasive Computing Systems class
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vangelidis.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
theme: minima

# User settings
username: Vasilis Angelidis
user_description: I am the coordination of the IT department of the Centre of Greek Sign Language. I design and implement innovating tools for Sign Language Training. Also I am project management in various cooperative projects.
user_title: Software Engineer
# email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: vasileios-angelidis-97745820a
github_username:  vangelidis
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
