# Site settings
title: Vasilis Angelidis
description: My bio | 1st assessment of the Mobile and Pervasive Computing Systems class
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vangelidis.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
theme: minima

# User settings
username: Vasilis Angelidis
user_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
# email: lorem_ipsum
# twitter_username: lorem_ipsum
# instagram_username: lorem_ipsum
# facebook_username: lorem_ipsum
linkedin_username: 
github_username:  
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
